language: c

before_install:
  - sudo bash -c "echo deb http://badgerports.org precise main >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E1FAD0C
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel

install:
  - mozroots --import --sync --quiet
  - mono ./.paket/paket.bootstrapper.exe 
  - mono ./.paket/paket.exe restore

script:
  - mkdir artifacts --parents
  - xbuild ./ScriptCs.sln /property:Configuration=Release /nologo /verbosity:normal
  - mono ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe test/ScriptCs.Tests.Acceptance/bin/Release/ScriptCs.Tests.Acceptance.dll /xml artifacts/ScriptCs.Tests.Acceptance.dll.TestResult.xml /html artifacts/ScriptCs.Tests.Acceptance.dll.TestResult.html

notifications:
  email:
    - adam@adamralph.com

